[package]
name = "vira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "4.0.0"
crossterm="0.27.0"
clap = { version = "4.0.32", features = ["derive"] }

